---
    - name: Installs nginx web server
      apt:
        name: nginx
        state: present
        update_cache: true
      notify:
        - start nginx

    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
# tasks file for nginx